# based on this commit, but adjusted to our needs
# https://github.com/conda-forge/uwsgi-feedstock/blob/7034c31b4e54a910fbdfbef2790c3d16235a5b37/recipe/meta.yaml


{% set name = "uWSGI" %}
{% set version = "2.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/uWSGI/uwsgi-{{ version }}.tar.gz
  sha256: 4972ac538800fb2d421027f49b4a1869b66048839507ccf0aa2fda792d99f583

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python {{ python }}                # [build_platform != target_platform]
    - cross-python_{{ target_platform }} # [build_platform != target_platform]
    - numpy                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake=3.19.6
    - jom  # [win]
    - make  # [unix]
    - pkg-config  # [unix]
    - gxx_linux-64 # [unix]
    - sysroot_linux-64=2.17 # [unix]
  host:
    - python {{ python }}
    - jansson
    - libxml2=2.9.12  # [not win]
    - openssl=1.1.1m
    - pcre=8.45
    - icu=58.2
    - yaml
    - zlib
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}

    - jansson

test:
  source_files:
    - tests
  commands:
    - uwsgi --version
    - uwsgi --plugin-list

about:
  home: https://github.com/unbit/uwsgi
  license: GPL-2.0
  license_file: LICENSE
  summary: |
    The uWSGI project aims at developing a full stack for building hosting
    services. Application servers (for various programming languages and
    protocols), proxies, process managers and monitors are all implemented.

extra:
  recipe-maintainers:
    - motoharu-yano
